# Generated by Django 4.2.11 on 2025-03-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('f_id', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(max_length=255)),
                ('accessibility_txt', models.CharField(max_length=255)),
                ('ada_accessibility', models.BooleanField()),
                ('reservation_url', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
