# Generated by Django 5.1.6 on 2025-03-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='reservation_url',
        ),
        migrations.AlterField(
            model_name='facility',
            name='accessibility_txt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='ada_accessibility',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
