name: campmate-cs4300-ey35p
services:
  - name: web
    image:
      registry_type: DOCKER_HUB
      repository: ghcr.io/${GHCR_USERNAME}/${GHCR_REPO}
      tag: latest
    run_command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8080
    envs:
      - key: DJANGO_SECRET_KEY
        value: ${DJANGO_SECRET_KEY}
      - key: DJANGO_SETTINGS_MODULE
        value: "camp_mate.docker_settings"
    volume_mounts:
      - volume_name: appdata
        mount_path: /app/data
volumes:
  - name: appdata
    size: 5Gi