# Generated by Django 4.2.11 on 2025-03-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favorited_loc',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorited_loc',
            field=models.ManyToManyField(blank=True, to='home.facility'),
        ),
    ]
