# Generated by Django 4.2.11 on 2025-04-21 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facility",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="tripdetails",
            name="facility",
        ),
        migrations.AddField(
            model_name="tripdetails",
            name="facility",
            field=models.ManyToManyField(blank=True, to="home.facility"),
        ),
    ]
