# Generated by Django 4.2.11 on 2025-04-02 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campground', models.BooleanField(default=True)),
                ('rangerstation', models.BooleanField(default=True)),
                ('hotel', models.BooleanField(default=True)),
                ('trail', models.BooleanField(default=True)),
                ('reservable', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='amenity_pref',
        ),
        migrations.DeleteModel(
            name='Amenity',
        ),
    ]
