# Generated by Django 4.2.20 on 2025-04-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_facility_latitude_facility_longitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="Primary image URL from RIDB API MEDIA",
                max_length=500,
                null=True,
            ),
        ),
    ]
