# Generated by Django 4.2.11 on 2025-04-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userpreferences_remove_userprofile_amenity_pref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='facility',
            field=models.BooleanField(default=True),
        ),
    ]
