# Generated by Django 4.2.11 on 2025-04-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userpreferences_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='reservable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facility',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
