# Generated by Django 4.2.11 on 2025-04-08 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_tripdetails'),
        ('home', '0004_facility_reservable_facility_url'),
    ]

    operations = [
    ]
