# Generated by Django 4.2.11 on 2025-04-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_merge_20250408_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripdetails',
            name='facility',
        ),
        migrations.AddField(
            model_name='tripdetails',
            name='facility',
            field=models.ManyToManyField(blank=True, to='home.facility'),
        ),
    ]
