# Generated by Django 4.2.11 on 2025-04-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_tripdetails_facility_tripdetails_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
