name: Django CI/CD

on:     # When to run this workflow
  push:  # Runs on every commit to any branch
    branches:
      - '**'
  pull_request:  # Runs on every pull request to main
    branches:
      - 'main'
    types:
      - closed  # Triggers only when a pull request to main has been merged

jobs:       # The steps to run
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository  
        uses: actions/checkout@v2

      - name: Set up Python  
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.3

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests with Coverage
        run: |
          coverage run --source=camp_mate,home manage.py test home.tests
          coverage report --fail-under=80 --omit="*/migrations/*,*/manage.py,*/wsgi.py"

      - name: Upload Coverage Report as Artifact  
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
          if-no-files-found: ignore  

  deploy:
    needs: build  #makes sure deploy only runs if build passes
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true  # Only deploy when merging to 'main' branch

    steps:
      - name: Deploy to Production  
        run: |
          # Add your deployment script or commands here
