name: Build, Push and Deploy a Docker Image

on:
  push:
    branches: [cd_pipeline] ## swap to main or PR to main
                            ### Currently testing efficacy of pipeline

permissions:
  contents: read
  packages: write

jobs:
  build-push-deploy-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6.5.0
        with:
          context: .
          push: true
          tags: ghcr.io/${{ secrets.LOWERCASE_GHCR_REPO }}:latest
      
      - name: Prepare app spec dynamically
        run: |
          export GHCR_USERNAME=${{ secrets.GHCR_USERNAME }}
          export GHCR_REPO=${{ secrets.GHCR_REPO }}
          export DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
          envsubst < .do/template.app.yaml > .do/app.yaml
      
      - name: Deploy the app
        uses: digitalocean/app_action/deploy@v2
        env:
          SAMPLE_DIGEST: ${{ steps.push.outputs.digest }}
        with:
          token: ${{ secrets.DO_API_TOPAZ }}
