name: OpenAI Code Review

on:
  pull-request: 
    branches:
      - main


jobs:
  ai-code-review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
    uses: acitions/checkout@v2

    -name: Set up Python
    uses: actions/setup-python@v2
    with:
      python-version: 3.12.8

    - name: Install dependencies
        run: |
          pip install openai PyGithub GitPython

    - name: Run review
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      run: python scripts/code_review.py